ch(redux):setup-redux
atlp-rwanda/bravo-bn-fe pull request #10
Opened 2022-07-27 20:23 UTC by Placide123

set up redux
example of a counter

[ready for review #182201667]

2022-07-28 07:22 UTC, uwambajeddy approved these changes

2022-07-28 07:29 UTC, semy-tuyi approved these changes

2022-08-01 09:28 UTC, joshwambere requested changes

2022-08-01 09:28 UTC, joshwambere commented on src/redux/counter/Counter.js
> +import React from 'react'
since this file has nothing to do with redux config it just uses redux there is no need to put it inside redux folder you can have it in components folder

2022-08-01 09:28 UTC, joshwambere commented on src/components/App.js
> +<h1>Welcome to Barefoot Nomad</h1>,
remove that colon

2022-08-01 09:28 UTC, joshwambere commented on src/index.js
> +<App />
Please lint before pushing

2022-08-02 07:31 UTC, joshwambere approved these changes

2022-08-02 07:31 UTC, merged