setup react router
atlp-rwanda/bravo-bn-fe pull request #13
Opened 2022-07-31 09:16 UTC by semy-tuyi

##  What does this PR do?

- set up react-router

##  Description of Task to be completed?

- setting react router for accessing different components through different routes

## How should this be manually tested?

- Clone the repo.

- checkout to a branch called ` [ch-setup-react-router-#182201670](https://github.com/atlp-rwanda/bravo-bn-fe/tree/ch-setup-react-router-%23182201670)`.

- Run npm install to install modules.

- Run `npm run start:dev` to run an app.

-create new component , give it a route 
-Try to access it through browser

2022-07-31 17:45 UTC, uwambajeddy requested changes
`components folder` should have included `child components` of the `base components`  and also `view folder` should have contained `base components`

2022-08-01 10:31 UTC, uwambajeddy approved these changes
LGTM

2022-08-01 10:55 UTC, alaintresor approved these changes

2022-08-01 12:24 UTC, joshwambere requested changes

2022-08-01 12:24 UTC, joshwambere commented on coverage/clover.xml
> +<?xml version="1.0" encoding="UTF-8"?>
why did you push coverage folder on the repo

2022-08-01 12:24 UTC, joshwambere commented on src/routes/index.js
> +import React from "react";
this All routes file might end up being a gigantic ones you might want to try a different approach

2022-08-02 04:41 UTC, uwambajeddy requested changes
you forgot to ignore  coverage folder

2022-08-02 04:56 UTC, semy-tuyi commented
<img width="295" alt="Screen Shot 2022-08-02 at 06 44 41" src="https://user-images.githubusercontent.com/92625609/182294690-45a95503-7d70-40e4-bb85-cae4f818b2da.png">
<img width="364" alt="Screen Shot 2022-08-02 at 06 42 02" src="https://user-images.githubusercontent.com/92625609/182294780-45ba5b62-6b9d-47d1-9a18-50e9bc0d4710.png">
any suggestion of how I can remove that coverage folder?

2022-08-02 11:19 UTC, joshwambere requested changes

2022-08-02 11:19 UTC, joshwambere commented on package.json
> -    "react-test-renderer": "^18.2.0"
why did you remove this dependency

2022-08-02 11:19 UTC, joshwambere commented on src/routes/index.js
> +            element: <Nav />,
nav should not be in here since is not a route itself

2022-08-02 11:19 UTC, joshwambere commented on src/routes/index.js
> +            children: [
those are routes by themselves should be independent

2022-08-02 11:19 UTC, joshwambere commented on src/routes/index.js
> +        {
you should have a root route `/` associated to `home`

2022-08-02 11:19 UTC, joshwambere commented on src/App.js
> +import React from 'react'
if this file what is does is simply importing routes i think you can merge it with indes.js a

2022-08-02 11:19 UTC, joshwambere commented on src/App.js
> +            <Router />
nav should be in here

2022-08-03 12:07 UTC, uwambajeddy approved these changes

2022-08-03 12:31 UTC, Placide123 approved these changes

2022-08-03 13:48 UTC, alaintresor approved these changes

2022-08-04 09:05 UTC, joshwambere requested changes

2022-08-04 09:05 UTC, joshwambere commented on src/App.js
> +            <Counter />
Please move this counter into home component

2022-08-08 11:35 UTC, joshwambere approved these changes

2022-08-08 11:35 UTC, joshwambere approved these changes

2022-08-08 11:40 UTC, merged