Ft user login #182201678
atlp-rwanda/bravo-bn-fe pull request #18
Opened 2022-08-03 11:41 UTC by alaintresor

#### What does this PR do?
User login frontend

#### How should this be manually tested?

- Clone the repo.
- Run npm install to install modules.
- Run npm start to run an app.
#### What are the relevant pivotal tracker stories?
https://www.pivotaltracker.com/story/show/182201678
#### Screenshots 
![Screenshot (49)](https://user-images.githubusercontent.com/55650162/182599169-abdc1962-99d4-489b-8b1c-91e0f39afed4.png)

2022-08-09 12:19 UTC, joshwambere requested changes

2022-08-09 12:19 UTC, joshwambere commented on src/views/Login.js
> +          swal.fire('Oops...', `${err.response.data.message}`, 'error');
may be redirect to other page instead of firing this modal

2022-08-09 12:19 UTC, joshwambere commented on src/views/Login.js
> +                            <p>Forgot password?</p>
increase this text fontSize

2022-08-09 12:19 UTC, joshwambere commented on src/redux/store.js
> +// eslint-disable-next-line import/prefer-default-export
remove this comment

2022-08-09 12:19 UTC, joshwambere commented on src/tests/mocks/handlers/auth.handler.js
> +    console.log("doneeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee")
remove this console

2022-08-09 12:19 UTC, joshwambere commented on src/views/Login.js
> +      axios.post('https://bravo-bfn-be.herokuapp.com/api/v1/user/login', {
use backend url from env

2022-08-09 12:19 UTC, joshwambere commented on src/views/Login.js
> +/* eslint-disable no-unused-vars */
why did you disable this eslint rurle?

2022-08-10 10:47 UTC, uwambajeddy approved these changes

2022-08-10 11:28 UTC, Patricknshimiyimana approved these changes

2022-08-10 13:48 UTC, joshwambere approved these changes

2022-08-10 13:48 UTC, merged