#182201677 Feature:reset-password
atlp-rwanda/bravo-bn-fe pull request #19
Opened 2022-08-04 15:18 UTC by Placide123

user should provide his email
user provides password for reset

[WIP #182201677]

2022-08-16 14:11 UTC, joshwambere requested changes
![Screenshot from 2022-08-16 15-59-55](https://user-images.githubusercontent.com/59834399/184900724-bb2a6201-b53d-459f-ac34-6a0e1c87a449.png)


and also the feature is not working as expected 
![Screenshot from 2022-08-16 16-01-01](https://user
![Screenshot from 2022-08-16 16-01-30](https://user-images.githubusercontent.com/59834399/184900865-eb62ff20-486b-464a-9504-bb434be57501.png)
![Screenshot from 2022-08-16 16-01-30](https://user-images.githubusercontent.com/59834399/184900965-9f74d80b-5f15-4d96-9972-5cb723e7fd1e.png)

2022-08-16 14:14 UTC, joshwambere commented
> ![Screenshot from 2022-08-16 15-59-55](https://user-images.githubusercontent.com/59834399/184900724-bb2a6201-b53d-459f-ac34-6a0e1c87a449.png)
> 
> and also the feature is not working as expected ![Screenshot from 2022-08-16 16-01-01](https://user ![Screenshot from 2022-08-16 16-01-30](https://user-images.githubusercontent.com/59834399/184900865-eb62ff20-486b-464a-9504-bb434be57501.png) ![Screenshot from 2022-08-16 16-01-01](https://user-images.githubusercontent.com/59834399/184901726-7f0b873a-4f48-4b38-9b8c-25f94e3ab319.png)

also use storybook for re-usable components like inputs and buttons

2022-08-19 15:22 UTC, uwambajeddy reviewed
Responsiveness
![Screenshot (494)](https://user-images.githubusercontent.com/59047760/185652484-473495a9-a01e-4ce9-ae0f-7f315b086668.png)
![Screenshot (492)](https://user-images.githubusercontent.com/59047760/185652498-2e77f4d2-b983-4c18-a1a7-af92a36c8c20.png)

2022-08-23 10:30 UTC, uwambajeddy approved these changes

2022-08-23 11:45 UTC, mwisemarierose approved these changes

2022-08-23 13:02 UTC, didasmbalanya requested changes
What is this image for ? src/assets/placide.jpeg

2022-08-23 13:02 UTC, didasmbalanya commented on src/components/App.js
> +// };
Why is App commented out ?

2022-08-23 13:02 UTC, didasmbalanya commented on src/components/Button/Button.js
> +// Inside src/components/Button/Button.js
what is this comment for. ?

2022-08-23 13:02 UTC, didasmbalanya commented on src/components/Input/Input.js
> +// import "../../styles/stories/Button.stories.scss";
Remove commented code if not needed

2022-08-23 13:02 UTC, didasmbalanya commented on src/styles/stories/button.stories.scss
> +// }
remove unused commented code

2022-08-23 13:02 UTC, didasmbalanya commented on src/views/Respassword.js
> +    console.log(formErrors);
remove console.log

2022-08-24 13:49 UTC, merged