feature#182201681-implement requests table
atlp-rwanda/bravo-bn-fe pull request #20
Opened 2022-08-07 16:28 UTC by Patricknshimiyimana

#### What does this PR do?
 - Implement user travel requests table
#### Description of Task to be completed?
 - create travel requests component
 - create table using mui
#### How should this be manually tested?
 - clone this repository
 - checkout to this branch `ft-requests-table-182201681`
 - run `npm install` to install dependencies
 - run `npm start` to start the application

#### What are the relevant pivotal tracker stories?
 - I used mui because it is the best, clean and easier implementation 
 I could find online
#### What are the relevant pivotal tracker stories?
 - https://www.pivotaltracker.com/n/projects/2569105/stories/182201681
#### Screenshots(If appropriate)

2022-08-12 08:05 UTC, semy-tuyi requested changes
Improve coverage

2022-08-12 08:05 UTC, semy-tuyi commented on src/components/dashboard/Dashboard.js
> +      {/* <Toolbar /> */}
leave this comment

2022-08-12 09:45 UTC, Patricknshimiyimana commented
> Improve coverage

Working on that
Thanks.

2022-08-18 11:52 UTC, alaintresor approved these changes

2022-08-18 13:15 UTC, uwambajeddy requested changes
Even though you had no figma UI to reference on but atleast there some features that are supposed to look similar 
![Screenshot (188)](https://user-images.githubusercontent.com/59047760/185404016-7e96259d-cb9a-44ad-bf99-c591d286d6e1.png)

2022-08-19 15:13 UTC, Patricknshimiyimana commented
> Even though you had no figma UI to reference on but atleast there some features that are supposed to look similar ![Screenshot (188)](https://user-images.githubusercontent.com/59047760/185404016-7e96259d-cb9a-44ad-bf99-c591d286d6e1.png)

Hello @uwambajeddy please note that we are using a mui table and I'm using the dashboard @mwisemarierose designed so that we have the same dashboard

2022-08-24 09:12 UTC, joshwambere approved these changes

2022-08-24 09:36 UTC, merged