#182201676 ft-signup-182201676: allow users to create accounts in the system
atlp-rwanda/bravo-bn-fe pull request #22
Opened 2022-08-11 14:47 UTC by uwambajeddy

##  What does this PR do?
- Allow user to create new accounts
##  Description of Task to be completed?
- fetch `API` from the backend
## How should this be manually tested?
- Clone the repo.
- Run `npm install` to install modules.
- Run `npm start` to run an app.
- Navigate to `/signup` and create an account

## What are the relevant pivotal tracker stories?
 - https://www.pivotaltracker.com/n/projects/2569105/stories/182201676

2022-08-12 15:07 UTC, Placide123 requested changes
on my end it is not running other can check

2022-08-15 21:22 UTC, uwambajeddy commented
> on my end it is not running other can check

Please let's be professional this section is for `requested changes` how am I supposed to know the issue if you didn't indicate it?

2022-08-16 13:57 UTC, joshwambere requested changes

2022-08-16 13:57 UTC, joshwambere commented on src/views/Signup.jsx
> +                                <input type="email" name="" placeholder="Email" value={userRequest.email} onChange={(event)=> setUserRequest({...userRequest,email: event.target.value})}  />
why did you not use stories for input while you created a story component

2022-08-16 13:57 UTC, joshwambere commented on src/views/Signup.jsx
> +                            </div>
also create a story for buttons

2022-08-16 13:57 UTC, joshwambere commented on src/views/Signup.jsx
> +      axios.post(`${process.env.API_URL}/user/auth/signup`, {
use redux for handling request with the backend

2022-08-16 13:57 UTC, joshwambere commented on src/views/Signup.jsx
> +  const [userRequest, setUserRequest] = useState({buttonDisable:false,email:'',lastName:'',role:'requester',phoneNumber:'',gender:'select',password:'',repeatPassword:'',firstName:'',userName:''});
this kind of state will be a headache to maintain, group information which are related

2022-08-18 10:02 UTC, semy-tuyi approved these changes
Looks Good

2022-08-18 10:02 UTC, Placide123 requested changes
work on responsiveness 
<img width="1440" alt="Screen Shot 2022-08-18 at 11 52 36" src="https://user-images.githubusercontent.com/86245638/185369107-817a28c6-154f-46a3-931f-74bc4e9f47ae.png">

and send is not working at my end
<img width="1440" alt="Screen Shot 2022-08-18 at 11 54 00" src="https://user-images.githubusercontent.com/86245638/185369222-0b302b91-f92f-4a3e-a7c7-9768d584f55f.png">

2022-08-18 10:56 UTC, alaintresor approved these changes

2022-08-18 12:55 UTC, Patricknshimiyimana commented
> and send is not working at my end <img alt="Screen Shot 2022-08-18 at 11 54 00" width="1440" src="https://user-images.githubusercontent.com/86245638/185369222-0b302b91-f92f-4a3e-a7c7-9768d584f55f.png">

I think the problem is in your webpack configuration ask @uwambajeddy to give you his version of webpack  file he is using

2022-08-18 14:05 UTC, joshwambere requested changes

2022-08-18 14:05 UTC, joshwambere commented on src/service/validations/signup.js
> +
those validations are a too much of vanilla javascript maybe take a look in this blog https://dev.to/codebucks/form-validation-in-reactjs-by-building-reusable-custom-hook-1bg7, or consider a third party form validation library

2022-08-19 08:41 UTC, semy-tuyi approved these changes

2022-08-19 12:25 UTC, Patricknshimiyimana reviewed
The create account button is doing nothing on my side

2022-08-19 13:45 UTC, alaintresor approved these changes

2022-08-19 16:18 UTC, Patricknshimiyimana approved these changes

2022-08-20 07:58 UTC, merged