feat(trip):Reject Trip Request
atlp-rwanda/bravo-bn-fe pull request #28
Opened 2022-08-18 12:15 UTC by alaintresor

#### What does this PR do?
Reject Trip request by manager
#### How should this be manually tested?

- clone
- npm install
- npm start

#### What are the relevant pivotal tracker stories?
https://www.pivotaltracker.com/story/show/182201685
#### Screenshot
![Screenshot (52)](https://user-images.githubusercontent.com/55650162/185392126-72515709-a8d7-4aae-a686-074c7ddcc600.png)

2022-08-25 13:17 UTC, joshwambere requested changes
![Screenshot from 2022-08-25 15-06-01](https://user-images.githubusercontent.com/59834399/186674445-92ec6a46-4800-43fa-aff6-1010ff9e60f5.png)
filll the table in the remaining spaces,

![Screenshot from 2022-08-25 15-07-02](https://user-images.githubusercontent.com/59834399/186674888-1547c470-2e9d-416c-9d08-32221948dbbd.png)

this modal does not resember the other modal we have in the system tweak it a little bit

2022-08-25 13:17 UTC, joshwambere commented on src/redux/requests/selectedRequestSlice.js
> +      console.log("hhhhhhhhhhhhhhhhhhhhhhhhh");
delete this

2022-08-25 13:18 UTC, joshwambere commented on src/redux/requests/selectedRequestSlice.js
> +      console.log("hhhhhhhhhhhhhhhhhhhhhhhhh");
also when rejecting or accepting please add some kind of loader to show the user something is happening

2022-08-30 08:57 UTC, joshwambere requested changes, later dismissed
Rebase, and find reason why trip request are not getting loaded on initial mounting of trip request component

2022-08-31 20:39 UTC, Patricknshimiyimana approved these changes

2022-09-01 06:41 UTC, mwisemarierose approved these changes

2022-09-01 06:59 UTC, Placide123 approved these changes

2022-09-01 08:42 UTC, merged