Ft avail requests for approval #182201687
atlp-rwanda/bravo-bn-fe pull request #29
Opened 2022-08-22 14:31 UTC by mwisemarierose

## What does this PR do?
approve Trip request by manager

## How should this be manually tested?
clone
npm install
npm start
## What are the relevant pivotal tracker stories?
https://www.pivotaltracker.com/story/show/182201687

2022-08-31 17:24 UTC, uwambajeddy approved these changes

2022-09-01 10:30 UTC, alaintresor approved these changes

2022-09-01 10:58 UTC, didasmbalanya requested changes
![Screen Shot 2022-09-01 at 13 55 08](https://user-images.githubusercontent.com/22627452/187897965-b99a61a7-f190-42b5-9b8e-66da7305e45b.png)

render the correct data for the `destination` column.

Make sure the titles for the table are consistent. If capial or small. Not camelCase

2022-09-02 07:43 UTC, didasmbalanya commented
Please fix the search functionality for the table!

2022-09-02 10:05 UTC, didasmbalanya requested changes, later dismissed
error on the console, seems like its triggered on text change


`index_bundle.js:2 Uncaught Error: Minified Redux error #7; visit https://redux.js.org/Errors?code=7 for the full message or use the non-minified dev environment for full errors. 
    at m (index_bundle.js:2:616707)
    at index_bundle.js:2:618006
    at onChange (index_bundle.js:102:92714)
    at onChange (index_bundle.js:75:125963)
    at Object.Oe (index_bundle.js:2:388780)
    at Ze (index_bundle.js:2:388934)
    at index_bundle.js:2:408794
    at Yr (index_bundle.js:2:408888)
    at Pr (index_bundle.js:2:409302)
    at index_bundle.js:2:414730`

2022-09-02 11:44 UTC, merged