#182201710 ft-notification-toast: pop up notification to alert the user
atlp-rwanda/bravo-bn-fe pull request #30
Opened 2022-08-24 07:58 UTC by uwambajeddy

##  What does this PR do?
- pop up notification to alert the user

## How should this be manually tested?
- Clone the repo.
- Run `npm install` to install modules.
- Run `npm start` to run an app.
- Navigate to `/login` to view  alerts

## What are the relevant pivotal tracker stories?
 - https://www.pivotaltracker.com/n/projects/2569105/stories/182201710

2022-08-25 14:12 UTC, joshwambere requested changes
You only shows toast on login page when there is not real notification please do some real implementation eg  `when a user is successfully logged in show a success toast and on fail do so`, replace the bulky existing toast

2022-08-25 14:57 UTC, uwambajeddy commented
> [<img alt="@joshwambere" width="20" height="20" src="https://avatars.githubusercontent.com/u/59834399?s=60&amp;u=b241b5ae466ccdf3e3af863bcbaf41b2f56be41c&amp;v=4">](/joshwambere) [joshwambere](/joshwambere) added [ rebase ](/atlp-rwanda/bravo-bn-fe/labels/rebase) Rebasing the codes[ changes needed ](/atlp-rwanda/bravo-bn-fe/labels/changes%20needed) and removed [ Ready For Review ](/atlp-rwanda/bravo-bn-fe/labels/Ready%20For%20Review) The Pull request is ready for reviewlabels [44 minutes ago](#event-7259937080)
> ## Merge state
> Add more commits by pushing to the `[ft-notification-toast-182201710](/atlp-rwanda/bravo-bn-fe/tree/ft-notification-toast-182201710)` branch on [atlp-rwanda/bravo-bn-fe](/atlp-rwanda/bravo-bn-fe).
> 
> Show environments
> ### This branch was successfully deployed
> 1 active deployment
> Show all reviewers
> ### Changes requested
> 1 review requesting changes by reviewers with write access. [Learn more.](https://docs.github.com/articles/about-pull-request-reviews/)
> ** 1 change requested **
> ** 3 pending reviewers **
> Show all checks
> ### All checks have passed
> 4 successful checks
> [ Resolve conflicts ](/atlp-rwanda/bravo-bn-fe/pull/30/conflicts)
> ### This branch has conflicts that must be resolved
> Use the command line to resolve conflicts before continuing.
> #### Conflicting files
> `package-lock.json`
> `package.json`
> `src/redux/store.js`
> `src/views/Login.jsx`
> Merge pull request
> You can also [open this in GitHub Desktop](x-github-client://openRepo/https://github.com/atlp-rwanda/bravo-bn-fe?branch=ft-notification-toast-182201710) or view command line instructions .
> 
> [<img alt="@uwambajeddy" width="40" height="40" src="https://avatars.githubusercontent.com/u/59047760?s=80&amp;v=4">](/uwambajeddy)
> 
> Add heading textAdd bold text, <Ctrl+b>Add italic text, <Ctrl+i>
> Add a quote, <Ctrl+Shift+.>Add code, <Ctrl+e>Add a link, <Ctrl+k>
> Add a bulleted list, <Ctrl+Shift+8>Add a numbered list, <Ctrl+Shift+7>Add a task list, <Ctrl+Shift+l>
> Directly mention a user or team
> Reference an issue, pull request, or discussion
> Add saved reply
> 
> 
> Attach files by dragging & dropping, selecting or pasting them.[ ](https://docs.github.com/github/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax)Styling with Markdown is supported
>  Close pull request
> Comment
> Remember, contributions to this repository should follow our [GitHub Community Guidelines](https://docs.github.com/articles/github-community-guidelines).
>  **ProTip!** Add comments to specific lines under [Files changed](/atlp-rwanda/bravo-bn-fe/pull/30/files).
> Reviewers
> [ <img alt="@joshwambere" width="20" height="20" src="https://avatars.githubusercontent.com/u/59834399?s=40&amp;v=4"> ](/joshwambere) [ joshwambere ](/joshwambere) [ ](/atlp-rwanda/bravo-bn-fe/pull/30/files/2f21afb3c5ae336df413ffe848753c9abfe14a55)
> 
> [ <img alt="@alaintresor" width="20" height="20" src="https://avatars.githubusercontent.com/u/55650162?s=40&amp;v=4"> ](/alaintresor) [ alaintresor ](/alaintresor)
> 
> [ <img alt="@semy-tuyi" width="20" height="20" src="https://avatars.githubusercontent.com/u/92625609?s=40&amp;v=4"> ](/semy-tuyi) [ semy-tuyi ](/semy-tuyi)
> 
> [ <img alt="@Patricknshimiyimana" width="20" height="20" src="https://avatars.githubusercontent.com/u/73250459?s=40&amp;v=4"> ](/Patricknshimiyimana) [ Patricknshimiyimana ](/Patricknshimiyimana)
> 
> Requested changes must be addressed to merge this pull request.
> 
> Still in progress? Convert to draft
> Assignees
> [ <img alt="@uwambajeddy" width="20" height="20" src="https://avatars.githubusercontent.com/u/59047760?s=40&amp;v=4"> ](/uwambajeddy) [ uwambajeddy ](/uwambajeddy)
> 
> Labels
> [ changes needed ](/atlp-rwanda/bravo-bn-fe/labels/changes%20needed) [ rebase ](/atlp-rwanda/bravo-bn-fe/labels/rebase)Rebasing the codes
> Projects
> None yet
> Milestone
> No milestone
> Development
> Successfully merging this pull request may close these issues.
> 
> None yet
> 
> Notifications
> Customize
>  Unsubscribe
> You’re receiving notifications because you were assigned.
> 
> 2 participants
> [ <img alt="@uwambajeddy" width="26" height="26" src="https://avatars.githubusercontent.com/u/59047760?s=52&amp;v=4"> ](/uwambajeddy) [ <img alt="@joshwambere" width="26" height="26" src="https://avatars.githubusercontent.com/u/59834399?s=52&amp;v=4"> ](/joshwambere)
>  **Lock conversation**

2022-08-25 15:01 UTC, uwambajeddy commented
> You only shows toast on login page when there is not real notification please do some real implementation eg `when a user is successfully logged in show a success toast and on fail do so`, replace the bulky existing toast

I think that will require a fix PR for login

2022-08-30 16:49 UTC, didasmbalanya approved these changes

2022-08-30 16:49 UTC, merged