#182201709 ft-edit-open-requests: allow users to update pending trip requests
atlp-rwanda/bravo-bn-fe pull request #31
Opened 2022-08-24 12:17 UTC by uwambajeddy

##  What does this PR do?
- pop up notification to alert the user

## How should this be manually tested?
- Clone the repo.
- Run `npm install` to install modules.
- Run `npm start` to run an app.
- navigate to `/booking`
- you must have a pending a trip request to update it

## What are the relevant pivotal tracker stories?
 - https://www.pivotaltracker.com/n/projects/2569105/stories/182201709

2022-08-25 13:58 UTC, joshwambere requested changes
![Screenshot from 2022-08-25 15-56-20](https://user-images.githubusercontent.com/59834399/186684420-50f7b631-a1f7-45cb-a292-34066bc6c772.png)
dont you think you need some kind of pagination here?, and date trip request was created on

2022-08-25 14:07 UTC, joshwambere requested changes
![Screenshot from 2022-08-25 16-04-38](https://user-images.githubusercontent.com/59834399/186686571-511435a3-e283-40df-a49a-e6ff6e0b36af.png)

why is it saying unauthorized to update trip request dont you think you should only show the user his trip-requests

2022-08-25 15:09 UTC, uwambajeddy commented
> ![Screenshot from 2022-08-25 16-04-38](https://user-images.githubusercontent.com/59834399/186686571-511435a3-e283-40df-a49a-e6ff6e0b36af.png)
> 
> why is it saying unauthorized to update trip request dont you think you should only show the user his trip-requests

 you logged as an admin, they are the only ones to view all trip requests!!

2022-08-29 16:38 UTC, Patricknshimiyimana approved these changes

2022-08-31 12:40 UTC, joshwambere approved these changes

2022-08-31 12:40 UTC, merged