create trip requests
atlp-rwanda/bravo-bn-fe pull request #34
Opened 2022-08-27 13:08 UTC by Patricknshimiyimana

#### What does this PR do?
 - Create trip requests
#### Description of Task to be completed?
 - create forms for request data
 - fetch locations, accomodations and rooms
#### How should this be manually tested?
 - clone this repository
 - checkout to this branch `ft-create-requests-182201686`
 - run `npm install` to install dependencies
 - run `npm start` to start the application

#### What are the relevant pivotal tracker stories?
 - https://www.pivotaltracker.com/n/projects/2569105/stories/182201686
#### Screenshots(If appropriate)

2022-08-30 11:43 UTC, joshwambere requested changes
![Screenshot from 2022-08-30 13-39-52](https://user-images.githubusercontent.com/59834399/187427557-4096714d-1082-49d1-9de4-c78a097c6f8a.png)

what is the use of those steps indicators if they are not working

- also date inputs are bigger than other inputs address that
- put some padding in text-area
- after successfully creating trip navigate to list of trip request

2022-08-30 11:47 UTC, joshwambere requested changes
![Screenshot from 2022-08-30 13-44-45](https://user-images.githubusercontent.com/59834399/187428520-f08592e6-fbc6-4f04-843e-285b9f24c9ea.png)

- Error message on description should float left and be in red color as others

2022-08-30 18:22 UTC, Patricknshimiyimana commented
> what is the use of those steps indicators if they are not working
> 
> * also date inputs are bigger than other inputs address that
> * put some padding in text-area
> * after successfully creating trip navigate to list of trip request

Resolved thanks!

2022-08-31 09:38 UTC, joshwambere approved these changes

2022-08-31 09:38 UTC, alaintresor approved these changes

2022-08-31 09:39 UTC, merged