chore(empty-react-project
atlp-rwanda/bravo-bn-fe pull request #5
Opened 2022-07-26 16:06 UTC by mwisemarierose

## What does this PR do?

Creates  react project from scratch using Webpack 4, Babel, and the Airbnb linting option

## How should this be manually tested?
clone this repository
npm i
npm run start

## What are the relevant pivotal tracker stories?
https://www.pivotaltracker.com/n/projects/2569105

2022-07-26 17:37 UTC, Placide123 approved these changes

2022-07-26 17:41 UTC, Placide123 requested changes
other is working fine but if app.js is removed in the component folder it can be good and put it into src

2022-07-26 19:13 UTC, uwambajeddy approved these changes

2022-07-27 07:50 UTC, joshwambere approved these changes
assets folder contains static assets like images videos icons etc, may be you can remove index.js and add random image or icon

2022-07-27 08:12 UTC, joshwambere requested changes

2022-07-27 08:12 UTC, joshwambere commented on src/components/App.js
> +class App extends Component {
use functional components instead of class based components

2022-07-27 08:12 UTC, joshwambere commented on .eslintrc.json
> +{
you have lint in the project and yet you pushed codes which has linting errors, and linting was not working as expected

2022-07-27 13:32 UTC, joshwambere approved these changes

2022-07-27 13:32 UTC, merged

2022-07-27 14:19 UTC, Placide123 approved these changes