chore#182201674 configure storybook for components development
atlp-rwanda/bravo-bn-fe pull request #8
Opened 2022-07-27 15:56 UTC by Patricknshimiyimana

#### What does this PR do?
 - configure storybook for component development
#### Description of Task to be completed?
 - initialize storybook
 - create an initial example story
#### How should this be manually tested?
 - clone this repository
 - checkout to this branch `ch-configure-storybook-182201674`
 - run `npm install` to install dependencies
 - run `npm run storybook` to start storybook
 - open it in the browser on `http://localhost:6007/` or any other specified port it might be running on 
to see the storybook interface
#### What are the relevant pivotal tracker stories?
 - https://www.pivotaltracker.com/n/projects/2569105/stories/182201674
#### Screenshots(If appropriate)
> <img width="400" alt="Screen Shot 2022-07-27 at 17 54 44" src="https://user-images.githubusercontent.com/73250459/181293329-7613902f-0d2a-4dee-bde1-58dcbca1c21d.png">

2022-07-28 05:10 UTC, alaintresor approved these changes

2022-07-28 06:50 UTC, uwambajeddy approved these changes

2022-08-01 10:28 UTC, joshwambere requested changes
can you maybe and use those stories you created so that others can know how to use it

2022-08-01 12:45 UTC, joshwambere reviewed
sorry for this review it come late but don't you think it makes more sens to use `scss`  and put all styles in `styles` folder and may be create sub-folder if you need them

2022-08-01 15:38 UTC, Patricknshimiyimana commented
> sorry for this review it come late but don't you think it makes more sense to use `scss` since we have already configured, and put all styles in `styles` folder and may be create sub-folder if you need them

Done!

2022-08-02 11:06 UTC, joshwambere approved these changes

2022-08-02 11:06 UTC, merged